config/routes.rb
StrategyStroller::Application.routes.draw do

  root :to => "home#index"
  match "home/index" => "home#index", :as => "home_index"  
  get "home/index"

 
  ActiveAdmin.routes(self)



  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :user


  

  
  match "controller_unit/input_framework/goals" => "controller_unit#set_goal", :as => "goals"
  match "controller_unit/input_framework/indicators" => "controller_unit#set_indicator", :as => "indicators"
  match "controller_unit/input_framework/projects" => "controller_unit#set_project", :as => "projects"
  match "controller_unit/cu_review" => "controller_unit#cu_review", :as => "cu_review"
  match "controller_unit/graph_panel" => "controller_unit#graph_panel", :as => "graph_panel"
  match "controller_unit/goal_check" => "controller_unit#goal_check", :as => 'goal_check'
  match "controller_unit/indicator_check" => "controller_unit#indicator_check", :as => 'indicator_check'
  match "controller_unit/project_check" => "controller_unit#project_check", :as => 'project_check'
  match "controller_unit/all_data" => "controller_unit#all_data", :as => 'all_data'
  match "controller_unit/all_activity" => "controller_unit#all_activity", :as => 'all_activity'
  match "controller_unit/all_project" => "controller_unit#all_project", :as => 'all_project'
  match "controller_unit/all_indicator" => "controller_unit#all_indicator", :as => 'all_indicator'
  match "controller_unit/all_goal" => "controller_unit#all_goal", :as => 'all_goal'
  match "controller_unit/all_dimension" => "controller_unit#all_dimension", :as => 'all_dimension'
  match "controller_unit/all_form" => "controller_unit#all_form", :as => 'all_form'

  match "provider/goal_define" => "provider#goal_define", :as => 'goal_define'
  match "provider/indicator_define" => "provider#indicator_define", :as => 'indicator_define'
  match "provider/project_define" => "provider#project_define", :as => 'project_define'
  match "provider/activity_define" => "provider#activity_define", :as => 'activities'
  match "provider/indicator_update" => "provider#indicator_update", :as => 'indicator_update'
  match "provider/project_update" => "provider#project_update", :as => 'project_update'
  match "provider/home" => "provider#forms_composite", :as => "forms_composite"
  match "provider/update" => "provider#forms_composite_update", :as => "forms_composite_update"
  match "provider/activity_edit" => "provider#activity_edit", :as => 'activity_edit'

  post "controller_unit/setup_system" => "controller_unit#applications", :as => "applications"
  post "controller_unit/create_users" => "controller_unit#applications"
  post "controller_unit/remove_users" => "controller_unit#applications"
  get "controller_unit/setup_system" => "controller_unit#setup_system", :as => "setup_system"
  get "controller_unit/create_users" => "controller_unit#create_users", :as => "create_users"
  get "controller_unit/remove_users" => "controller_unit#remove_users", :as => "remove_users"
  get "controller_unit/edit_users" => "controller_unit#edit_users", :as => "edit_users"











end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :rememberable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable, #end defaults (I removed rememberable, so no cookies. can back later.)
         :confirmable, :timeoutable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :business_code, :temp_password, :controlling_unit

  # these validations are redundant - they're ensured through a combination of the database migration/definition and in
  # devise.rb initializer and in the :validatable module. Put here for documentation mainly.
  # validates :email, :presence => true
  # validates :password, :presence => true, :length => { :minimum => 10, :maximum => 128 }

  # TODO add in :username:string, :cu:boolean fields.
  
  ### ASSOCIATIONS (added 03/28/2013)
  has_many :goals
  has_many :indicators
  has_many :owned_projects, :class_name => "Project", :foreign_key => :head_id
  has_many :steering_projects, :class_name => "Project", :foreign_key => :steer_id
  has_many :forms
  
  ### VALIDATIONS (added 04/16/2013)
  # Business code = string[10]
  validates :business_code,
  :length => { :maximum => 10 }

  validates_uniqueness_of :email
  
  ### TODO: NOTE TO SELF
  ## If you see this note, make sure to only give T/F options
  ## Rails has this thing where most things default to False 

  ## Controlling Unit = true / false = yes / no
  validates :controlling_unit, :inclusion => { :in => [true, false] }
  
end

app/controllers/controller_unit_controller.rb
class ControllerUnitController < ApplicationController
  require 'base64' 
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction, :sort_column2

  GOAL = 1
  INDICATOR = 2
  PROJECT = 3
  ACTIVITY = 4
  MAILER = ActionMailer::Base.default_url_options

  def clean_list(listie)
    final_list = []
    i = 0
    listie.each do |k|
      y=i.times.map{0}<<k
      final_list<<y
      i = i+1
    end
    return final_list
  end

  def graph_panel
    @user = current_user
    pname_list = Project.all.map(&:short_name)
    pgs_list_uc = Project.all.map(&:status_global)
    len_of_list = pname_list.length
    if len_of_list>0
      max_val = pgs_list_uc.max
      axis_range = "0" + "|" + (max_val/4).to_s + "|" + (max_val/2).to_s + "|" + (3*max_val/4).to_s + "|" + max_val.to_s
      colors = len_of_list.times.map{"%06x" % (rand * 0x1000000)}
      pgs_list = pgs_list_uc.combination(1).to_a

      ### Line chart still relies on canned data.
      @line_chart = Gchart.line(:size => '600x200',:data => [300, 100, 30, 200, 100, 200, 300, 10], :axis_with_labels => '',
              :axis_labels => ['Jan|July|Jan|July|Jan', axis_range], :title => "Projects Status Trends",)

      spacing = (350/(len_of_list)).to_s + "," + (150/(len_of_list)).to_s
      @bar_chart = Gchart.bar( 
              :axis_with_labels => 'y',
              :axis_labels => [axis_range],
              :size => '500x600',
              :theme => :pastel,
              :title => "Projects Global Status",
              :bar_width_and_spacing => '7,5',
              :legend => pname_list,
              :data => clean_list(pgs_list_uc))

      @pie_chart = Gchart.pie_3d(:title => 'Project Status Distribution', :size => '600x230',
                :data => pgs_list_uc, :labels => pname_list )
    end
  end
  
  def set_goal
    @goal = Goal.new
    if (request.post?)
      @goal = Goal.new(params[:goal])
      @goal.status = 0
      if @goal.save # goal saved
        form_id = save_form(GOAL, @goal.user_id, @goal.id)
        if (!form_id) # goal saved but form not saved, so delete goal #TODO will never fail, since goal is hard- coded and it is the only thing it can fail on. No uniqueness, etc.
          Goal.delete(Goal.find_by_id(@goal.id))
          flash[:error] = "ERROR: Goal was not saved!"
        else # goal and form saved
          provider = @goal.user.username
          flash[:notice] = "Goal successfully saved! A form has been sent to " + provider + "."
          @user_obj = User.find_by_id(@goal.user_id)
          @form_url = encode_url(form_id, @goal.id)
          #save form_url
          FormMailer.form_email(@user_obj,@form_url).deliver #Mail confirmation to each saved user
        end
      else # goal not saved
        flash[:error] = "ERROR: Goal was not saved! Please fill out all required fields." #CHANGED 5/6/2013
      end
      redirect_to all_form_path
    end
  end
  
  def set_indicator  #FIXME MERGE
    @indicator = Indicator.new
    if (request.post?)
      params[:indicator][:goal_ids].delete("")
      @indicator = Indicator.new(params[:indicator])
      @indicator.status = 0
      @indicator.contributing_projects_status = 0
      @indicator.actual = 0
      @indicator.target = 1
      @indicator.prognosis = 0
      @indicator.diff = 0
      @indicator.reported_values = []
      @indicator.freq = []
      if @indicator.save # indicator saved
        form_id = save_form(INDICATOR, @indicator.user_id, @indicator.id)
        if (!form_id) # indicator saved but form not saved, so delete indicator
          Indicator.delete(Indicator.find_by_id(@indicator.id))
          flash[:error] = "ERROR: Indicator was not saved!"
        else # indicator and form saved
          provider = @indicator.user.username
          flash[:notice] = "Indicator successfully saved! A form has been sent to " + provider + "."
          @user_obj = User.find_by_id(@indicator.user_id)
          # Need to populate a form
          @form_url = encode_url(form_id, @indicator.id)
          FormMailer.form_email(@user_obj,@form_url).deliver #Mail confirmation to each saved user
        end
      else # indicator not saved
        flash[:error] = "ERROR: Indicator was not saved! Please fill out all required fields." #CHANGED 5/6/2013
      end
      redirect_to all_form_path
    end
  end
  
  def set_project
    @project = Project.new
    if (request.post?)
      params[:project][:indicator_ids].delete("")
      @project = Project.new(params[:project])
      # Put some (important) default values
      @project.startDate = Date.current
      @project.endDate = Date.tomorrow
      @project.actual_duration = 0
      @project.target_duration = 1
      @project.status_cost = 0
      @project.status_global = 0
      @project.status_manp = 0
      @project.update_status_ms #will set status_ms to default value.
      @project.status_prog = 0
      @project.target_cost = 0
      @project.actual_cost = 0
      @project.target_manp = 0
      @project.actual_manp = 0
      @project.yearly_target_manp = {}
      @project.yearly_target_cost = {}
      if @project.save # project saved
        form_id = save_form(PROJECT, @project.head_id, @project.id)
        if (!form_id) # project saved but form not saved, so delete project
          Project.delete(Project.find_by_id(@project.id))
          flash[:error] = "ERROR: Project was not saved!"
        else # project and form saved
          provider = @project.head.username
          flash[:notice] = "Project successfully saved! A form has been sent to " + provider + "."
          @user_obj = User.find_by_id(@project.head_id)
          # Need to populate a form
          @form_url = encode_url(form_id, @project.id)
          FormMailer.form_email(@user_obj,@form_url).deliver #Mail confirmation to each saved user
        end
      else # project not saved
        flash[:error] = "ERROR: Project was not saved! Please fill out all required fields." #CHANGED 5/6/2013
      end
      redirect_to all_form_path
    end
  end

  def applications
    @application = Application.new
    if (request.post?)
      if (params[:commit] == 'Save Setup')
          redirect_to "/controller_unit/setup_system"
          setup_system
      elsif (params[:commit] == 'Create User(s)')
          redirect_to "/controller_unit/create_users"
          create_users
      elsif (params[:commit] == 'Remove User(s)')
          redirect_to "/controller_unit/remove_users"
          remove_users
      end
    end
  end
  
    def setup_system
        @application = Application.new
        @years = Application::YEARS
        @languages = Application::LANGUAGES
        @time_horizon = Application::TIME_HORIZON
         if (request.post?) 
            @application = Application.new(params[:application])
            if @application.save
                flash[:notice] = "Setup successfully saved!"
            else
                flash[:error] = "ERROR: Setup was not saved"
                return
            end
        end
    end

    def encode_id(id) 
      encoded = Base64.encode64(id.to_s)
      return encoded
    end

    def encode_url(form_id, entry_id) #only for provider define (so far)
      encoded_form_id = encode_id(form_id.to_s)
      encoded_entry_id = encode_id(entry_id.to_s)
      form = Form.find_by_id(form_id)
      lookup = form.lookup
      if (lookup == GOAL) 
        category = "goal"
      elsif (lookup == INDICATOR)
        category = "indicator"
      elsif (lookup == PROJECT)
        category = "project"
      elsif (lookup ==  ACTIVITY)
        category = "activity"
      end
      url = MAILER[:host] + "/provider/" + category + "_define?entry_id=" + encoded_entry_id + "&form_id=" + encoded_form_id #temp
    end

    def create_users
       @application = Application.new #Just using Application model because it has a 'users' field that cocoon needs
        if (request.post?)
            app = params[:application]
            if (app != nil)
                users_hash = app[:users_attributes] #hash of hashes

                numSaved = 0 
                total = 0 #number of users that should be saved
                notSaved = []

                users_hash.each do |key, value|
                    username = users_hash[key][:username]
                    email = users_hash[key][:email]
                    if (email != "" && username != "") #quick check not from empty input boxes (or invalid)
                        total += 1
                      
                        temp_password = SecureRandom.hex
                        cu = users_hash[key][:controlling_unit]
                        user = User.new(:username => username, :email => email, :password => temp_password, :temp_password => temp_password, :controlling_unit => cu)
                        if user.save
                            numSaved += 1
                           user.send_confirmation_instructions #TODO TEST
                        else
                            notSaved << email
                        end
                    end
                end     

                if (numSaved == 0 && total == 0) #empty input boxes
                    flash[:notice] = "Please enter Username and Email"
                elsif (numSaved == total) #tried to save valid inputs and success!
                    flash[:notice] = "All users successfully saved!"
                else #some users could not be saved
                    user_string = ""
                    notSaved.each do |user|
                        user_string = user_string + user + ", "
                    end
                    user_string.slice!(user_string.length - 2)
                    flash[:notice] = "User(s) " + user_string + "already exist(s). All other users successfully created!"
                end
            else
                flash[:notice] = "No users saved"
            end
         end
    end

    def remove_users

app/helpers/controller_unit_helper.rb
module ControllerUnitHelper
  
  ## INFO
  GOAL = 1
  INDICATOR = 2
  PROJECT = 3
  ACTIVITY = 4
   
  def find_path_cu(table_id, entry_id, form_id)
    if table_id == GOAL
      return goal_check_path(:entry_id => entry_id, :form_id => form_id)
    elsif table_id == INDICATOR
      return indicator_check_path(:entry_id => entry_id, :form_id => form_id)
    elsif table_id == PROJECT
      return project_check_path(:entry_id => entry_id, :form_id => form_id)
    else
      ## ERROR: Should not reach here!
      return cu_review_path
    end
  end

  def save_form(table_id, user_id, entry_id)
    default = [GOAL,INDICATOR,PROJECT,ACTIVITY]
    if default.include? table_id
      @form = Form.new(
          :checked => false,
          :lookup => table_id,
          :reviewed => false,
          :user_id => user_id,
          :submitted => false,
          :last_reminder => Date.today,
          :entry_id => entry_id
      )
      if @form.save
        return @form.id
      else   # FIXME due to the validations in form and the if above, this cannot be reached by this method.
        return nil
      end
    else
      # ERROR: wrong table_id
      return nil
    end
  end

end

app/views/controller_unit/_create_user_fields.html.erb
<div class='nested-fields'>
    <%= f.input :username, :label => (I18n.t :enter_user_name) %>
    <%= f.input :email, :label => (I18n.t :enter_user_email) %>
    <%= f.input :controlling_unit, :label => false, :input_html => { :class => "checkbox", :type => "checkbox" } %>
    <%= link_to_remove_association "Remove User", f %><br>
</div>

app/views/controller_unit/all_data.html.erb
<div class="navbar snb nocorner">
	<div class="navbar-inner ni nocorner">
		<div class="container">
			<ul class="nav isnb">
				<li class="active">
					<a href=<%= url_for all_data_path %>><%= t '.data_view' %></a>
				</li>
				<li >
					<a href=<%= url_for graph_panel_path %>><%= t '.graphs' %></a>
				</li>
			</ul>
		</div>
	</div>
</div><!-- /.navbar
<h2><%= t '.hi_controlling', :user_username => (@user.username) %>! </h2>
<%= t '.here_is_all' %>
<br />

<br />-->

<div class="well nocorner keybar">
	<span class="label label-info nocorner">
		<center>
			<%= t :dimension %>
		</center></span>
	<span class="label label-info nocorner">
		<center>
			<%= t :goal %>
		</center></span>
	<span class="label label-info nocorner">
		<center>
			<%= t :indicator %>
		</center></span>
	<span class="label label-info nocorner">
		<center>
			<%= t :project %>
		</center></span>
</div>

<div class="tree">
	<ul>
		<% Dimension.all.each do |d| %>
		<li class = "li_tree_dim">
			<div class="tree_dim">
				<% if d.status >= 1 %>
				<span class="label label-success treebadge nocorner">
				<% elsif d.status >= 0.9 %>
				<span class="label label-warning treebadge nocorner">
				<% else %>
				<span class="label label-important treebadge nocorner">
				<% end %>
				<%= link_to d.name, all_dimension_path(:dimension_id => d.id) %> </span>
			</div>
			<ul>
				<% d.goals.each do |g| %>
				<li class = "li_tree_goal">
					<div class="tree_goal">
						<% if g.status >= 1 %>
						<span class="label label-success treebadge nocorner"> 
						<% elsif g.status >= 0.9 %> 
						<span class="label label-warning treebadge nocorner"> 
						<% else %> 
						<span class="label label-important treebadge nocorner"> 
						<% end %>
						<%= link_to g.name, all_goal_path(:goal_id => g.id) %> </span>
					</div>
					<ul>
						<% g.indicators.each do |i| %>
						<li class = "li_tree_indic">
							<div class="tree_indic">
								<% if i.status >= 1 %>
								<span class="label label-success treebadge nocorner"> 
								<% elsif i.status >= 0.9 %> 
								<span class="label label-warning treebadge nocorner"> 
								<% else %> 
								<span class="label label-important treebadge nocorner"> 
								<% end %>
								<%= link_to i.name, all_indicator_path(:indicator_id => i.id) %> </span>
							</div>
							<ul>
								<% i.projects.each do |p| %>
								<li class = "li_tree_proj">
									<div class="tree_proj">
										<% if p.status_global >= 1 %>
										<span class="label label-success treebadge nocorner"> 
										<% elsif p.status_global >= 0.9 %> 
										<span class="label label-warning treebadge nocorner"> 
										<% else %> 
										<span class="label label-important treebadge nocorner"> 
										<% end %>
										<%= link_to p.name, all_project_path(:project_id => p.id) %> </span>
									</div>
								</li>
								<% end %>
							</ul>
						</li>
						<% end %>
					</ul>
				</li>
				<% end %>
			</ul>
		</li>
		<% end %>
	</ul>
</div>
<br />
<br />
<br />
<br />
<br />

app/views/controller_unit/all_dimension.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<a class="brand" href="#"><%= t '.dimension_view' %></a>
		</ul>
	</div>
</div>
<style>
	input {
		width: 25em;
	}
	textarea {
		width: 50em;
	}
</style>

<%= render "setup_alerts" %>
<div class="well">
    <%= semantic_form_for @dimension, :url => all_dimension_path do |f| %>
        <%= f.inputs do %>
        <%= hidden_field_tag :entry_id, params[:entry_id] %>
        <%= hidden_field_tag :form_id, params[:form_id] %>
	<div class="row-fluid">
		<div class="span6">     
          <%= f.input :name, :input_html => { :value => @dimension.name, :readonly => true, :class => "span12" }, :label => (I18n.t :name_of_dimension) %>
		</div>
		<div class="span6">          
          <%= f.input :status, :input_html => { :value => @dimension.status, :readonly => true, :class => "span12" }, :label => (I18n.t :current_status) %>
		</div>
	</div>          
    <% end %>
	<center>
		<div class="row-fluid">
			<input type=button class="btn btn-danger span4" value= "<%= I18n.t :back%>" onclick= "history.back()">
			</input>
		</div>
	</center>
    <% end %>
</div>

app/views/controller_unit/all_project.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<a class="brand" href="#"><%= t '.project_view' %></a>
		</ul>
	</div>
</div>
<style>
	input {
		width: 25em;
	}
	textarea {
		width: 50em;
	}
</style>

<%= render "setup_alerts" %>
<div class="well">
	<%= semantic_form_for @project, :url => all_project_path do |f| %>
	<%= f.inputs do %>
	<%= hidden_field_tag :entry_id, params[:entry_id] %>
	<%= hidden_field_tag :form_id, params[:form_id] %>
	<div class="row-fluid">
		<div class="span8">
			<%= f.input :name, :input_html => { :value => @project.name, :readonly => true, :class => "span12" }, :label => (I18n.t :name_of_project) %>
		</div>
		<div class="span4">
			<%= f.input :short_name, :input_html => { :value => @project.short_name, :readonly => true, :class => "span12" }, :label => (I18n.t :short_name_of_project) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :indicator_ids, :as => :select, :collection => Indicator.all, :selected => @project.indicator_ids, :input_html => { :disabled => true, :class => "span12", :multiple => true }, :label => (I18n.t :associated_indicators) %>
		</div>
		<div class="span6">
			<%= f.input :head_id, :as => :select, :collection => User.where(:controlling_unit => false), :selected => @project.head_id, :input_html => { :disabled => true, :class => "span12" }, :label => (I18n.t :project_manager) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :description, :input_html => { :value => @project.description, :readonly => true, :class => "span12", :rows => 5 }, :label => (I18n.t :project_description) %>
		</div>
		<div class="span6">
			<%= f.input :startDate, :input_html => { :value => @project.startDate, :disabled => true, :class => "span4" }, :label => (I18n.t :starting_date) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<table class="table table-hover table-bordered">
				<tr>
					<th><%= t '.activity_3' %></th>
					<th><%= t '.current_1' %></th>
				</tr>
		
				<% @activities.each do |a| %>
				<tr>
					<td valign="top"><%= link_to a.name, all_activity_path(:activity_id => a.id) %></td>
					<td>
					<div class="progress">
						<div class="bar" style="width: 60%;"></div>
					</div></td>
				</tr>
				<% end %>
			</table>
		</div>
		<div class="span6">
			<div class="span6">
			<%= f.input :actual_manp, :value => 40, :input_html => { :value => @project.actual_manp, :class => "span12", :disabled => true }, :label => (I18n.t :actual_employee_resources_days) %>
			</div>
			<div class="span6">
			<%= f.input :actual_cost, :value => 30, :input_html => { :value => @project.actual_cost, :class => "span12", :disabled => true }, :label => (I18n.t :actual_external_costs_currency) %>
			</div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :notes, :input_html => { :value => @project.notes, :readonly => true, :class => "span12", :rows => 5 }, :label => (I18n.t :notes) %>
		</div>
		<div class="span6">
			<div class="span6">
				<%= f.input :inplan, :as => :boolean, :input_html => { :checked => @project.inplan, :disabled => true }, :checked_value => true, :unchecked_value => false, :label => (I18n.t :included_in_financial_plan) %>
			</div>
			<div class="span6">
				<%= f.input :compensation, :input_html => { :checked => @project.compensation, :disabled => true }, :checked_value => true, :unchecked_value => false,:label => (I18n.t :compensation_possible) %>
			</div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6"></div>
		<div class="span6">
			<div class="span4">
				<%= f.input :target_manp, :input_html => { :value => @project.target_manp, :readonly => true, :class => "span12" }, :label => (I18n.t :planned_employee_resources_days) %>
			</div>
			<div class="span4">
				<%= f.input :actual_manp, :input_html => { :value => @project.actual_manp, :readonly => true, :class => "span12" }, :label => (I18n.t :actual_employee_resources_days) %>
			</div>
			<div class="span4">
				<%= f.input :status_manp, :input_html => { :value => @project.status_manp, :readonly => true, :class => "span12" }, :label => (I18n.t :current_status_by_manpower_use) %>
			</div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6"></div>
		<div class="span6">
			<div class="span4">
				<%= f.input :target_cost, :input_html => { :value => @project.target_cost, :readonly => true, :class => "span12" }, :label => (I18n.t :planned_external_costs_currency) %>
			</div>
			<div class="span4">
				<%= f.input :actual_cost, :input_html => { :value => @project.actual_cost, :readonly => true, :class => "span12" }, :label => (I18n.t :actual_external_costs_currency) %>
			</div>
			<div class="span4">
				<%= f.input :status_cost, :input_html => { :value => @project.status_cost, :readonly => true, :class => "span12" }, :label => (I18n.t :current_status_by_cost) %>
			</div>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6"></div>
		<div class="span6">
			<div class="span6">
				<%= f.input :target_duration, :input_html => { :value => @project.target_duration, :readonly => true, :class => "span12" }, :label => (I18n.t :project_target_duration_months) %>
			</div>
			<div class="span6">
				<%= f.input :status_ms, :input_html => { :value => @project.status_ms, :readonly => true, :class => "span12" }, :label => (I18n.t :current_status_by_milestone) %>
			</div>
		</div>
    </div>

	<div class="row-fluid">
		<div class="span6"></div>
		<div class="span6">
			<%= f.input :status_notes, :input_html => { :value => @project.status_notes, :readonly => true, :class => "span12", :rows => 5 }, :label => (I18n.t :notes_to_current_status) %>
		</div>
	</div>
	<% end %>
	<center>
		<div class="row-fluid">
			<input type=button class="btn btn-danger span4" value= "<%= I18n.t :back%>" onclick= "history.back()">
			</input>
		</div>
	</center>
	<% end %>
</div>

app/views/controller_unit/create_users.html.erb
<style>
	.checkbox {
		margin-left: 5px;
   		margin-right: 5px;
	}
</style>
<div class="navbar">
	<div class="navbar-inner">
		<a class="brand" href="#"><%= t '.create_users' %></a>
		</ul>
	</div>
</div>
<%= render "setup_alerts" %>
<div class="well">
		<div class="row-fluid">
			<div class="span4 offset5">
				<!-- Need to specify company position and general position (CU/prov) when entering a user-->
				<%= semantic_form_for @application do |f| %>
				<%= f.inputs do %>
				<%= f.semantic_fields_for :users do |user| %>
				<%= render 'create_user_fields', :f => user %>
				<% end %>
				<%= link_to_add_association 'Add User', f, :users, :partial => 'create_user_fields', :data => {"association-insertion-position" => "before", "association-insertion-node" => "this"} %>
				<% end %>
				<br/><br/>
				<%= f.action :submit, :label => (I18n.t :create_user_s ) %><% end %>
			</div>
		</div>
</div>

app/views/controller_unit/delete_users.html.erb
<h1><%= t '.delete_users' %></h1>
<!-- Need to specify company position and general position (CU/prov) when entering a user-->
<%= semantic_form_for @application do |f| %>
    <%= f.inputs do %>
       <%= f.semantic_fields_for :users do |user| %>
             <%= render 'delete_user_fields', :f => user %>
        <% end %>
        <%= link_to_add_association 'Delete User', f, :users, :data => {"association-insertion-position" => "before", "association-insertion-node" => "this"} %>

    <% end %>
    <%= f.action :submit, :label => (I18n.t :delete_user_s) %>
<% end %>