config/routes.rb
StrategyStroller::Application.routes.draw do

  root :to => "home#index"
  match "home/index" => "home#index", :as => "home_index"  
  get "home/index"

 
  ActiveAdmin.routes(self)



  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :user


  

  
  match "controller_unit/input_framework/goals" => "controller_unit#set_goal", :as => "goals"
  match "controller_unit/input_framework/indicators" => "controller_unit#set_indicator", :as => "indicators"
  match "controller_unit/input_framework/projects" => "controller_unit#set_project", :as => "projects"
  match "controller_unit/cu_review" => "controller_unit#cu_review", :as => "cu_review"
  match "controller_unit/graph_panel" => "controller_unit#graph_panel", :as => "graph_panel"
  match "controller_unit/goal_check" => "controller_unit#goal_check", :as => 'goal_check'
  match "controller_unit/indicator_check" => "controller_unit#indicator_check", :as => 'indicator_check'
  match "controller_unit/project_check" => "controller_unit#project_check", :as => 'project_check'
  match "controller_unit/all_data" => "controller_unit#all_data", :as => 'all_data'
  match "controller_unit/all_activity" => "controller_unit#all_activity", :as => 'all_activity'
  match "controller_unit/all_project" => "controller_unit#all_project", :as => 'all_project'
  match "controller_unit/all_indicator" => "controller_unit#all_indicator", :as => 'all_indicator'
  match "controller_unit/all_goal" => "controller_unit#all_goal", :as => 'all_goal'
  match "controller_unit/all_dimension" => "controller_unit#all_dimension", :as => 'all_dimension'
  match "controller_unit/all_form" => "controller_unit#all_form", :as => 'all_form'

  match "provider/goal_define" => "provider#goal_define", :as => 'goal_define'
  match "provider/indicator_define" => "provider#indicator_define", :as => 'indicator_define'
  match "provider/project_define" => "provider#project_define", :as => 'project_define'
  match "provider/activity_define" => "provider#activity_define", :as => 'activities'
  match "provider/indicator_update" => "provider#indicator_update", :as => 'indicator_update'
  match "provider/project_update" => "provider#project_update", :as => 'project_update'
  match "provider/home" => "provider#forms_composite", :as => "forms_composite"
  match "provider/update" => "provider#forms_composite_update", :as => "forms_composite_update"
  match "provider/activity_edit" => "provider#activity_edit", :as => 'activity_edit'

  post "controller_unit/setup_system" => "controller_unit#applications", :as => "applications"
  post "controller_unit/create_users" => "controller_unit#applications"
  post "controller_unit/remove_users" => "controller_unit#applications"
  get "controller_unit/setup_system" => "controller_unit#setup_system", :as => "setup_system"
  get "controller_unit/create_users" => "controller_unit#create_users", :as => "create_users"
  get "controller_unit/remove_users" => "controller_unit#remove_users", :as => "remove_users"
  get "controller_unit/edit_users" => "controller_unit#edit_users", :as => "edit_users"











end

app/models/application.rb
class Application < ActiveRecord::Base

  attr_accessible :company, :curr_year, :curr_qtr, :curr_month,:init_year, 
  :language, :time_horizon, :users
  has_many :users
  accepts_nested_attributes_for :users

  YEARS = [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
    2021, 2022, 2023, 2024, 2025]

  LANGUAGES = ["English", "German"]

  TIME_HORIZON = [2,3,4,5]

  # company
  validates :company,
  :presence => true
  
  # curr_year
  validates :curr_year,
  :presence => true
  # validate valid year?
  
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_goal_fields.html.erb
<div class='nested-fields'>
<!-- Choose one input and one interaction to dynamically generate -->
    <br><%= f.input :as => :select, :collection => [:name, :need, :justification, :focus, :notes, :status], :prompt => true %>
    <br><%= f.input :name, :label => (I18n.t :) %>
    <br><%= f.input :dimension_id, :label => (I18n.t :) %>
    <br><%= f.input :id, :label => (I18n.t :) %>
    <br><%= f.input :user_id, :label => (I18n.t :) %>
    <br><%= f.input :need, :label => (I18n.t :) %>
    <br><%= f.input :justification, :label => (I18n.t :) %>
    <br><%= f.input :focus, :label => (I18n.t :) %>

    <br><%= f.input :notes, :label => (I18n.t :) %>

    <br><%= f.input :status, :label => (I18n.t :) %>

</div>

app/views/forms/_user_fields.html.erb
<div class='nested-fields'>
    <%= f.input :email, :as => :select, :size => 10, :multiple => true, :label => (I18n.t :actor_email) %>
    <%= link_to_remove_association "Remove Actor", f %><br>
</div>

app/views/forms/form_template.html.erb
<h1> <%= t 'form_template' %> </h1>
<body>
  
    <%= semantic_form_for @form do |f| %>
        <%= f.inputs do %>
     
          <%= f.input :goal_id, :label => (t ".select_a_form") :as => :select, :collection => Form.all, :prompt => true, :required => true %>
          <!--<%= f.input :indicator_id, :label => (t ".pick_an_indicator"), :as => :select, :collection => Indicator.all, :prompt => true, :required => true %>-->
          <!--<%= f.input :project_id, :label => (t ".pick_a_project"), :as => :select, :collection => Project.all, :prompt => true, :required => true %>--> 

          <!--<%= f.input :user_ids, :as => :select, :size => 25, :multiple => true, :collection => User.all, :selected => User.first, :include_hidden => false, :label => (t ".select_providers_to_send") %>-->

        <% end %>
    <%= f.action :submit, :label => (t ".submit_form_to_project_owners")  %>
    <% end %>
</body>