config/routes.rb
StrategyStroller::Application.routes.draw do

  root :to => "home#index"
  match "home/index" => "home#index", :as => "home_index"  
  get "home/index"

 
  ActiveAdmin.routes(self)



  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :user


  

  
  match "controller_unit/input_framework/goals" => "controller_unit#set_goal", :as => "goals"
  match "controller_unit/input_framework/indicators" => "controller_unit#set_indicator", :as => "indicators"
  match "controller_unit/input_framework/projects" => "controller_unit#set_project", :as => "projects"
  match "controller_unit/cu_review" => "controller_unit#cu_review", :as => "cu_review"
  match "controller_unit/graph_panel" => "controller_unit#graph_panel", :as => "graph_panel"
  match "controller_unit/goal_check" => "controller_unit#goal_check", :as => 'goal_check'
  match "controller_unit/indicator_check" => "controller_unit#indicator_check", :as => 'indicator_check'
  match "controller_unit/project_check" => "controller_unit#project_check", :as => 'project_check'
  match "controller_unit/all_data" => "controller_unit#all_data", :as => 'all_data'
  match "controller_unit/all_activity" => "controller_unit#all_activity", :as => 'all_activity'
  match "controller_unit/all_project" => "controller_unit#all_project", :as => 'all_project'
  match "controller_unit/all_indicator" => "controller_unit#all_indicator", :as => 'all_indicator'
  match "controller_unit/all_goal" => "controller_unit#all_goal", :as => 'all_goal'
  match "controller_unit/all_dimension" => "controller_unit#all_dimension", :as => 'all_dimension'
  match "controller_unit/all_form" => "controller_unit#all_form", :as => 'all_form'

  match "provider/goal_define" => "provider#goal_define", :as => 'goal_define'
  match "provider/indicator_define" => "provider#indicator_define", :as => 'indicator_define'
  match "provider/project_define" => "provider#project_define", :as => 'project_define'
  match "provider/activity_define" => "provider#activity_define", :as => 'activities'
  match "provider/indicator_update" => "provider#indicator_update", :as => 'indicator_update'
  match "provider/project_update" => "provider#project_update", :as => 'project_update'
  match "provider/home" => "provider#forms_composite", :as => "forms_composite"
  match "provider/update" => "provider#forms_composite_update", :as => "forms_composite_update"
  match "provider/activity_edit" => "provider#activity_edit", :as => 'activity_edit'

  post "controller_unit/setup_system" => "controller_unit#applications", :as => "applications"
  post "controller_unit/create_users" => "controller_unit#applications"
  post "controller_unit/remove_users" => "controller_unit#applications"
  get "controller_unit/setup_system" => "controller_unit#setup_system", :as => "setup_system"
  get "controller_unit/create_users" => "controller_unit#create_users", :as => "create_users"
  get "controller_unit/remove_users" => "controller_unit#remove_users", :as => "remove_users"
  get "controller_unit/edit_users" => "controller_unit#edit_users", :as => "edit_users"











end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :rememberable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable, #end defaults (I removed rememberable, so no cookies. can back later.)
         :confirmable, :timeoutable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :business_code, :temp_password, :controlling_unit

  # these validations are redundant - they're ensured through a combination of the database migration/definition and in
  # devise.rb initializer and in the :validatable module. Put here for documentation mainly.
  # validates :email, :presence => true
  # validates :password, :presence => true, :length => { :minimum => 10, :maximum => 128 }

  # TODO add in :username:string, :cu:boolean fields.
  
  ### ASSOCIATIONS (added 03/28/2013)
  has_many :goals
  has_many :indicators
  has_many :owned_projects, :class_name => "Project", :foreign_key => :head_id
  has_many :steering_projects, :class_name => "Project", :foreign_key => :steer_id
  has_many :forms
  
  ### VALIDATIONS (added 04/16/2013)
  # Business code = string[10]
  validates :business_code,
  :length => { :maximum => 10 }

  validates_uniqueness_of :email
  
  ### TODO: NOTE TO SELF
  ## If you see this note, make sure to only give T/F options
  ## Rails has this thing where most things default to False 

  ## Controlling Unit = true / false = yes / no
  validates :controlling_unit, :inclusion => { :in => [true, false] }
  
end

app/controllers/provider_controller.rb
class ProviderController < ApplicationController
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction
  
  MAILER = ActionMailer::Base.default_url_options

 # def encode_url(form_id)
  #  encoded_id = encode_id(form_id.to_s)
   # url = "http://localhost:3000/forms?form_id=" + encoded_id.to_s #TEMP
  #end

  GOAL = 1
  INDICATOR = 2
  PROJECT = 3
  ACTIVITY = 4
   
  def goal_define
    @user = current_user
    @goal = Goal.new
    form_id = params[:form_id]
    entry_id = params[:entry_id]
    @current_form = Form.find_by_id(form_id)
    @current_goal = Goal.find_by_id(entry_id)
    @current_form.update_attributes(:checked => true)
    if (request.post?)
      if (params[:commit] == "Submit Goal")
        @current_form.update_attributes(:submitted => true, :updated_at => Time.current)
        @current_goal.update_attributes(params[:goal], :updated_at => Time.current)
        flash[:notice] = "Goal successfully submitted!"
      elsif (params[:commit] == "Save Goal")
        @current_goal.update_attributes(params[:goal])
        flash[:notice] = "Goal successfully saved!"
      end
      redirect_to forms_composite_path
    end
  end
  
  def indicator_define
    @user = current_user
    @indicator = Indicator.new
    form_id = params[:form_id]
    entry_id = params[:entry_id]
    @current_form = Form.find_by_id(form_id)
    @current_indicator = Indicator.find_by_id(entry_id)
    @current_form.update_attributes(:checked => true)
    @goal_short_names = (Goal.select('short_name')).collect{|g| g.short_name}
    if (request.post?)
      params[:indicator][:freq].delete_if{|k,v| k==""}
      params[:indicator][:freq].map! do |month|
          month = month.to_i
      end
      if (params[:commit] == "Submit Indicator")
        @current_indicator.update_attributes(params[:indicator], :updated_at => Time.current)
        @current_form.update_attributes(:submitted => true, :updated_at => Time.current)
        flash[:notice] = "Indicator successfully submitted!"
      elsif (params[:commit] == "Save Indicator")
         @current_indicator.update_attributes(params[:indicator])
        flash[:notice] = "Indicator successfully saved!"
      end
      redirect_to forms_composite_path
    end
  end
  
  def project_define
    session[:return_to] = request.url
    @user = current_user
    @project = Project.new
    form_id = params[:form_id]
    entry_id = params[:entry_id]
    @current_form = Form.find_by_id(form_id)
    @current_project = Project.find_by_id(entry_id)
    @current_form.update_attributes(:checked => true)
    @activities = @current_project.activities
    if (request.post?)
      if (params[:commit] == "Submit Project")
        @current_form.update_attributes(:submitted => true, :updated_at => Time.current)
        @current_project.update_attributes(params[:project], :updated_at => Time.current)
        flash[:notice] = "Project successfully submitted!"
      elsif (params[:commit] == "Save Project")
        @current_project.update_attributes(params[:project])
        flash[:notice] = "Project successfully saved!"
      end
      redirect_to forms_composite_path
    end
  end
  
  def activity_define
    @user = current_user
    @activity = Activity.new
    @project_id = params[:project_id]
    if (request.post?)
      # NOTE: activity don't need to be in form table
      # We can directly do lookup on activity table
      @activity = Activity.new(params[:activity])
      if @activity.save # activity saved
        flash[:notice] = "Activity successfully saved!"
      else # activity not saved
        flash[:error] = "ERROR: Activity was not saved!"
      end
      if session[:return_to]
         redirect_to session[:return_to]
      else
        redirect_to activities_path
      end
    end
  end
  
  def indicator_update
    @user = current_user
    @indicator = Indicator.new
    form_id = params[:form_id]
    entry_id = params[:entry_id]
    @current_form = Form.find_by_id(form_id)
    @current_indicator = Indicator.find_by_id(entry_id)
    @projects = (@current_indicator.projects).collect{|p| p.short_name}
    @projects.empty? ? @projects += ['None'] : nil
    if (request.post? || request.put?)
      reported_val = params[:indicator][:reported_values]
      if (@current_indicator.reported_values == nil)
        params[:indicator][:reported_values] =  reported_val.to_s
      else
        params[:indicator][:reported_values] = @current_indicator.reported_values << reported_val.to_f #Need to account for BIG VALUE
      end
      if (params[:commit] == "Update Indicator")
        @current_form.update_attributes(:reviewed => false)
        @current_indicator.update_attributes(params[:indicator], :updated_at => Time.current)
        flash[:notice] = "Indicator successfully submitted!"
      elsif (params[:commit] == "Save Indicator")
        @current_form.update_attributes(:reviewed => false)
        @current_indicator.update_attributes(params[:indicator]) #don't want to set updated_at if just saving ind
        flash[:notice] = "Indicator changes saved!"
      end
      redirect_to forms_composite_update_path
    end
  end

  def project_update
    session[:return_to] = request.url
    @user = current_user
    @project = Project.new
    @form_id = params[:form_id]
    @entry_id = params[:entry_id]
    @current_form = Form.find_by_id(@form_id)
    @current_project = Project.find_by_id(@entry_id)
    @activities = @current_project.activities
    @total_t_manp = 0
    @total_a_manp = 0
    @total_t_cost = 0
    @total_a_cost = 0
    
    if (request.post? || request.put?)
      if (params[:commit] == "Update")
        # just update activity
        @current_activity = Activity.find_by_id(params[:activity][:id])
        @current_activity.update_attributes(
          :actualManp => params[:activity][:actualManp],
          :actualCost => params[:activity][:actualCost],
          :actualProg => params[:activity][:actualProg],
          :updated_at => Time.current
        )
        flash[:notice] = "Activity successfully updated!"
        redirect_to project_update_path(:entry_id => @entry_id, :form_id => @form_id)
      else
        # update the project
        params[:project].delete(:random1) #randomx just used to display sum in view
        params[:project].delete(:random2)
        params[:project].delete(:random3)
        params[:project].delete(:random4)
        if (params[:commit] == "Update Project")
          @current_form.update_attributes(:reviewed => false)
          @current_project.update_attributes(params[:project], :updated_at => Time.current)
          flash[:notice] = "Project successfully submitted!"
        elsif (params[:commit] == "Save Project")
          @current_form.update_attributes(:reviewed => false)
          @current_project.update_attributes(params[:project]) #don't want to set updated_at if just saving proj
          flash[:notice] = "Project successfully saved!"
        end
        redirect_to forms_composite_update_path
      end
    end
  end
  
  def forms_composite
    @user = current_user
    @forms_unchecked = Form.order(sort_column + " " + sort_direction).where(:checked => false, :submitted=>false).find_all_by_user_id(@user.id)
    @forms_saved = Form.order(sort_column + " " + sort_direction).where(:checked => true, :submitted=>false).find_all_by_user_id(@user.id)
  end

  def forms_composite_update
    @user = current_user
    @all_ind_forms = Form.find_all_by_user_id_and_lookup(@user.id, INDICATOR)
    @indicator_forms = []
    @all_ind_forms.each do |form|
      ind = Indicator.find(form.entry_id)
      #make sure month is in freq and we haven't already updated the ind this month
      included = ind.freq.include?(Time.now.month) && (ind.updated_at.month != Time.now.month)
      if (form.submitted && form.checked && form.reviewed && included)
        @indicator_forms << form
      end
    end

    @all_proj_forms = Form.find_all_by_user_id_and_lookup(@user.id, PROJECT)
    @proj_forms = []
    @all_proj_forms.each do |form|
      proj = Project.find(form.entry_id)
      #make sure we haven't already updated the proj this month
      included = proj.updated_at.month != Time.now.month
      if (form.submitted && form.checked && form.reviewed && included)
        @proj_forms << form
      end
    end
  end

  def activity_edit
    @activity = Activity.find_by_id(params[:activity_id])
    if (request.post? || request.put?)
      @current_activity = Activity.find_by_name(params[:activity][:name])
      if (@current_activity.update_attributes(params[:activity]))
        flash[:notice] = "Activity successfully updated!"
      else
        flash[:error] = "ERROR: Activity not updated!"
      end
      if session[:return_to]
        redirect_to session[:return_to]
      else
        redirect_to activities_path
      end
    end
  end

  ### THE FOLLOWING ARE JUST HELPER METHODS ###
  private # Note at the top of this file
  
  # Code is taken from:
  # http://railscasts.com/episodes/228-sortable-table-columns
  # modified accordingly
  def sort_column
    Form.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end 
  
  # Code is taken as is from:
  # http://railscasts.com/episodes/228-sortable-table-columns
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
end

app/helpers/provider_helper.rb
module ProviderHelper
  
  ## INFO
  GOAL = 1
  INDICATOR = 2
  PROJECT = 3
  
  def find_path(table_id, entry_id, form_id)
    if table_id == GOAL
      return goal_define_path(:entry_id => entry_id, :form_id => form_id)
    elsif table_id == INDICATOR
      return indicator_define_path(:entry_id => entry_id, :form_id => form_id)
    elsif table_id == PROJECT
      return project_define_path(:entry_id => entry_id, :form_id => form_id)
    else
      ## ERROR: Should not reach here!
      return forms_composite_path
    end
  end

  def find_update_path(table_id, entry_id, form_id)
    if table_id == INDICATOR
      return indicator_update_path(:entry_id => entry_id, :form_id => form_id)
    elsif table_id == PROJECT
      return project_update_path(:entry_id => entry_id, :form_id => form_id)
    else
      ## ERROR: Should not reach here!
      return forms_composite_update_path
    end
  end
  
end

app/views/provider/_setup_alerts.html.erb
      <% if flash[:notice] or notice %>
          <% if notice == flash[:notice]%>
              <div class="alert" >
              <button type="button" class="close" data-dismiss="alert"><%= t 'times' %></button>
              <%= flash[:notice] %>
              </div>
          <% else %>
            <div class="notice alert">
			<button type="button" class="close" data-dismiss="alert"><%= t 'times' %></button>
			<%= flash[:notice] %>
            <%= notice %>
			</div>
          <% end %>
      <% end %>
      <% if flash[:error] or alert %>
            <% if flash[:error] == alert %>
                <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert"><%= t 'times' %></button>
                <%= flash[:error] %>
                </div>
            <% else %>
                <div class="alert  alert-error">
                <button type="button" class="close" data-dismiss="alert"><%= t 'times' %></button>
                <%= flash[:error] %>
                <%= alert %>
                </div>
			<% end %>
      <% end %>
	 

app/views/provider/activity_edit.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<a class="brand" href="#"><%= t '.activity_edit' %></a>
		</ul>
	</div>
</div>
<style>
	input {
		width: 25em;
	}
	textarea {
		width: 50em;
	}
</style>

<%= render "setup_alerts" %>
<div class="well">
	<%= semantic_form_for @activity, :url => activity_edit_path do |f| %>
	<%= f.inputs do %>
	<%= hidden_field_tag :entry_id, params[:entry_id] %>
	<%= hidden_field_tag :form_id, params[:form_id] %>

	<div class="row-fluid">
		<div class="span12">
			<%= f.input :name, :input_html => { :value => @activity.name, :class => "span12" }, :label => (I18n.t :name_of_activity) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :project_id, :as => :select, :collection => Project.all, :selected => @activity.project_id, :input_html => { :class => "span12" }, :label => (I18n.t :part_of_project) %>
		</div>
		<div class="span6">
			<%= f.input :short_name, :input_html => { :value => @activity.short_name, :class => "span12" }, :label => (I18n.t :short_name_of_activity) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :startDate, :input_html => { :value => @activity.startDate, :class => "span4" }, :label => (I18n.t :starting_date) %>
		</div>
		<div class="span6">
			<%= f.input :actualManp, :input_html => { :value => @activity.actualManp, :class => "span12" }, :label => (I18n.t :actual_employee_resources_days) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :endDate, :input_html => { :value => @activity.endDate,:class => "span4" }, :label => (I18n.t :ending_date) %>
		</div>
		<div class="span6">
			<%= f.input :actualCost, :input_html => { :value => @activity.actualCost, :class => "span12" }, :label => (I18n.t :actual_external_costs_currency) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :description, :input_html => { :value => @activity.description, :rows => 5, :class => "span12" }, :label => (I18n.t :activity_description) %>
		</div>
		<div class="span6">
			<%= f.input :team, :input_html => { :value => @activity.team, :rows => 5, :class => "span12" }, :label => (I18n.t :team_member) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :phase, :as => :select, :collection => [["0-Ongoing", 0], ["1-Concept completed", 1], ["2-Prerequisites fulfilled", 2], ["3-Implementation running", 3], ["4-Project in effect", 4]], :label => (I18n.t :part_of_phase), :input_html => { :class=> "span12" } %>
          <!--TODO add in phase string functionality. This will work for now.-->
		</div>
		<div class="span6">
			<%= f.input :notes, :input_html => { :value => @activity.notes, :rows => 5, :class => "span12" }, :label => (I18n.t :notes) %>
		</div>
	</div>

	<% end %>

	<center>
		<div class="row-fluid">
			<%= f.action :submit, :label => (I18n.t :submit_activity),:button_html => { :class=> "btn btn-primary span4" } %>
			<input type=button class="btn btn-danger span4" value= "<%= I18n.t :back%>" onclick= "history.back()">
			</input>
		</div>
	</center>

	<% end %>
</div>

app/views/provider/define_page.html.erb
<script>
document.getElementById("home").className = "";
document.getElementById("define_page").className = "active";
</script>

<% content_for :context_menu do %>
<li><a href="<%= url_for(:action => 'goal_define', :controller => 'provider') %>"><%= t '.goal' %></a></li>
<li><a href="<%= url_for(:action => 'indicator_define', :controller => 'provider') %>"><%= t '.indicator_1' %></a></li>
<li><a href="<%= url_for(:action => 'activity_define', :controller => 'provider') %>"><%= t '.activity' %></a></li>
<% end %>

<h2><%= t '.welcome_2', :user_username => (@user.username) %>! </h2>
<%= link_to (t '.unchecked_3'), unchecked_path %><br>
<%= link_to (t '.saved_forms_3'), saved_path %><br>

app/views/provider/project_define.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<a class="brand" href="#"><%= t '.project_form' %></a>
		</ul>
	</div>
</div>
<style>
	input {
		width: 25em;
	}
	textarea {
		width: 50em;
	}
</style>

<%= render "setup_alerts" %>
<div class="well">
	<%= semantic_form_for @project, :url => project_define_path do |f| %>
	<%= f.inputs do %>
	<%= hidden_field_tag :entry_id, params[:entry_id] %>
	<%= hidden_field_tag :form_id, params[:form_id] %>
	<div class="row-fluid">
		<div class="span8">
			<%= f.input :name, :input_html => { :value => @current_project.name, :disabled => true, :class => "span12" }, :label => (I18n.t :name_of_project) %>
		</div>
		<div class="span4">
			<%= f.input :short_name, :input_html => { :value => @current_project.short_name, :disabled => true, :class => "span12" }, :label => (I18n.t :short_name_of_project) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :indicator_ids, :as => :select, :collection => Indicator.all, :required => true, :selected => @current_project.indicator_ids, :input_html => { :disabled => true, :class => "span12", :multiple => true }, :label => (I18n.t :associated_indicator) %>
		</div>
		<div class="span6">
			<%= f.input :head_id, :as => :select, :collection => User.where(:controlling_unit => false), :required => true, :selected => @current_project.head_id, :input_html => { :disabled => true, :class => "span12" }, :label => (I18n.t :project_manager) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :description, :as => :text, :input_html => { :value => @current_project.description, :rows => 5, :class => "span12" }, :required => true, :label => (I18n.t :project_description) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<table class="table table-hover table-bordered">
				<tr>
					<th><%= t '.activity_name' %></th>
					<th><%= t '.current' %></th>
				</tr>
		
				<% @activities.each do |a| %>
				<tr>
					<td valign="top"><%= link_to a.name, activity_edit_path(:activity_id => a.id) %></td>
					<td>
					<div class="progress">
						<div class="bar" style="width: 60%;"></div>
					</div></td>
				</tr>
				<% end %>
				<tr class="info">
					<td><%= link_to (t '.create_new_1'), activities_path(:project_id => @current_project.id) %></td>
					<td></td>
				</tr>
			</table>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :notes, :as => :text, :input_html => { :value => @current_project.notes, :rows => 5, :class => "span12" }, :label => (I18n.t :notes) %>
		</div>
	</div>

	<br />
	<% end %>

	<center>
		<div class="row-fluid">
			<%= f.action :submit, :label => (I18n.t :submit_project),:button_html => { :class=> "btn btn-primary span4" }%>
			<%= f.action :submit, :label => (I18n.t :save_project),:button_html => { :class=> "btn btn-primary span4" }%>
		</div>
	</center>

	<% end %>
</div>

app/views/provider/project_update.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<a class="brand" href="#"><%= t '.project_form' %></a>
		</ul>
	</div>
</div>
<style>
	input {
		width: 25em;
	}
	textarea {
		width: 50em;
	}
</style>
<%= render "setup_alerts" %>
<div class="well">


	<%= semantic_form_for @project, :url => project_update_path do |f| %>
	<%= f.inputs do %>
	<%= hidden_field_tag :entry_id, params[:entry_id] %>
	<%= hidden_field_tag :form_id, params[:form_id] %>

	<div class="row-fluid">
		<div class="span8">
			<%= f.input :name, :input_html => { :value => @current_project.name, :class => "span12", :readonly => true }, :required => true, :label => (I18n.t :name_of_project) %>
		</div>
		<div class="span4">
			<%= f.input :short_name, :input_html => { :value => @current_project.short_name, :class => "span12", :readonly => true }, :required => true, :label => (I18n.t :short_name_of_project) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= f.input :indicator_ids, :as => :select, :collection => Indicator.all, :selected => @current_project.indicator_ids, :input_html => { :class => "span12", :disabled => true, :multiple => true }, :required => true, :label => (I18n.t :associated_indicator) %>
		</div>
		<div class="span6">
			<%= f.input :head_id, :as => :select, :collection => User.where(:controlling_unit => false), :selected => @current_project.head_id, :input_html => { :class => "span12", :disabled => true }, :required => true, :label => (I18n.t :project_manager) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span12">
			<table class="table table-hover table-bordered">
				<tr>
					<th><%= t '.activity' %></th>
					<th><%= t '.target' %></th>
					<th><%= t '.current' %></th>
					<th><%= t '.target_cost' %></th>
					<th><%= t '.current_cost' %></th>
					<th><%= t '.status' %></th>
					<th><%= t '.update' %></th>
				</tr>

				<% @activities.each do |a| %>
				<tr>
					<td class="span3" valign="top"><%= link_to a.name, all_activity_path(:activity_id => a.id) %></td>

					<%= semantic_form_for a, :url => project_update_path(:entry_id => @entry_id, :form_id => @form_id) do |f| %>

					<%= f.input :id, :as => :hidden, :value => a.id %>

					<td class="span1"><%= f.input :targetManp, :input_html => {:readonly => true, :class => "span24" }, :label => false %></td>
					<% @total_t_manp += a.targetManp %>
					<td class="span1"><%= f.input :actualManp,:input_html => {:class => "span24"}, :label => false %></td>
					<% @total_a_manp += a.actualManp %>
					<td class="span1"><%= f.input :targetCost, :input_html => {:readonly => true, :class => "span24" }, :label => false %></td>
					<% @total_t_cost += a.targetCost %>
					<td class="span1"><%= f.input :actualCost, :input_html => {:class => "span24"},:label => false %></td>
					<% @total_a_cost += a.actualCost %>
					<td class="span3"><%= f.input :actualProg, :collection => [["Not Yet Started", 0], ["In Progress", 1], ["Completed", 2]], :input_html => {:class => "span24"}, :allow_blank => false, :as => :select, :label => false %></td>

					<td class="span2"><%= f.action :submit, :label => (I18n.t :update),:button_html => {  :class=> "btn btn-info span12" } %></td>

					<% end %>

				</tr>
				<% end %>

				<tr>
					<td class="span3">Sum</td>
					<td class="span1"><%= f.input :random1, :input_html => {:value => @total_t_manp, :readonly => true, :class => "span24" }, :label => false %></td>
					<td class="span1"><%= f.input :random2,:input_html => {:value => @total_a_manp, :readonly => true, :class => "span24"}, :label => false %></td>
					<td class="span1"><%= f.input :random3, :input_html => {:value => @total_t_cost, :readonly => true, :class => "span24" }, :label => false %></td>
					<td class="span1"><%= f.input :random4, :input_html => {:value => @total_a_cost, :readonly => true, :class => "span24"},:label => false %></td>
					<td class="span3"></td><td class="span2"></td>
				</tr>
			</table>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span12">
			<%= f.input :status_notes, :as => :text, :input_html => { :value => @current_project.status_notes, :rows => 2, :class => "span12" }, :label => (I18n.t :status_notes) %>
		</div>
	</div>

	<br />

	<% end %>
	<center>
		<div class="row-fluid">
			<%= f.action :submit, :_method => :post, :label => (I18n.t :update_project),:button_html => {  :class=> "btn btn-primary span4" } %>
			<%= f.action :submit, :method => :post, :label => (I18n.t :save_project),:button_html => {  :class=> "btn btn-primary span4" } %>
			<input type=button class="btn btn-danger span4" value= "<%= I18n.t :cancel%>" onclick= "history.back()">
			</input>
		</div>

	</center>

	<% end %>


</div>


app/views/provider/provider_panel.html.erb
<h2><%= t '.welcome_1', :user_username => (@user.username) %>! </h2>
<%= link_to (t '.unchecked_2'), unchecked_path %><br>
<%= link_to (t '.saved_forms_2'), saved_path %><br>
<%= link_to (t '.create_new'), activities_path %><br>