config/routes.rb
StrategyStroller::Application.routes.draw do

  root :to => "home#index"
  match "home/index" => "home#index", :as => "home_index"  
  get "home/index"

 
  ActiveAdmin.routes(self)



  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :user


  

  
  match "controller_unit/input_framework/goals" => "controller_unit#set_goal", :as => "goals"
  match "controller_unit/input_framework/indicators" => "controller_unit#set_indicator", :as => "indicators"
  match "controller_unit/input_framework/projects" => "controller_unit#set_project", :as => "projects"
  match "controller_unit/cu_review" => "controller_unit#cu_review", :as => "cu_review"
  match "controller_unit/graph_panel" => "controller_unit#graph_panel", :as => "graph_panel"
  match "controller_unit/goal_check" => "controller_unit#goal_check", :as => 'goal_check'
  match "controller_unit/indicator_check" => "controller_unit#indicator_check", :as => 'indicator_check'
  match "controller_unit/project_check" => "controller_unit#project_check", :as => 'project_check'
  match "controller_unit/all_data" => "controller_unit#all_data", :as => 'all_data'
  match "controller_unit/all_activity" => "controller_unit#all_activity", :as => 'all_activity'
  match "controller_unit/all_project" => "controller_unit#all_project", :as => 'all_project'
  match "controller_unit/all_indicator" => "controller_unit#all_indicator", :as => 'all_indicator'
  match "controller_unit/all_goal" => "controller_unit#all_goal", :as => 'all_goal'
  match "controller_unit/all_dimension" => "controller_unit#all_dimension", :as => 'all_dimension'
  match "controller_unit/all_form" => "controller_unit#all_form", :as => 'all_form'

  match "provider/goal_define" => "provider#goal_define", :as => 'goal_define'
  match "provider/indicator_define" => "provider#indicator_define", :as => 'indicator_define'
  match "provider/project_define" => "provider#project_define", :as => 'project_define'
  match "provider/activity_define" => "provider#activity_define", :as => 'activities'
  match "provider/indicator_update" => "provider#indicator_update", :as => 'indicator_update'
  match "provider/project_update" => "provider#project_update", :as => 'project_update'
  match "provider/home" => "provider#forms_composite", :as => "forms_composite"
  match "provider/update" => "provider#forms_composite_update", :as => "forms_composite_update"
  match "provider/activity_edit" => "provider#activity_edit", :as => 'activity_edit'

  post "controller_unit/setup_system" => "controller_unit#applications", :as => "applications"
  post "controller_unit/create_users" => "controller_unit#applications"
  post "controller_unit/remove_users" => "controller_unit#applications"
  get "controller_unit/setup_system" => "controller_unit#setup_system", :as => "setup_system"
  get "controller_unit/create_users" => "controller_unit#create_users", :as => "create_users"
  get "controller_unit/remove_users" => "controller_unit#remove_users", :as => "remove_users"
  get "controller_unit/edit_users" => "controller_unit#edit_users", :as => "edit_users"











end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title><%= t '.strategy' %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">

		<%= stylesheet_link_tag    "application", :media => "all" %>

		<%= javascript_include_tag "application" %>
		<!-- Only use application for all js files or individual calls for each to prevent duplication
		<%= javascript_include_tag "custom" %>-->
		<!-- Added for cocoon gem -->
		<!--<%= javascript_include_tag :cocoon %>-->
		<!--<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
		<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
		<script src="/assets/twitter/bootstrap/bootstrap-dropdown.js">-->

		<%= csrf_meta_tags %>

		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="../assets/js/html5shiv.js"></script>
		<![endif]-->
	</head>

	<body>

		<div class="navbar navbar-inverse navbar-fixed-top mainnav">

			<div class="navbar-inner">
				<div class="container">
					<a class="brand" href="/"><%= t '.strategy_1' %></a>
					<% if signed_in? %>
					<% if current_user.respond_to?('controlling_unit') %>
					<% if current_user.controlling_unit == true %>
					<!-- <div id ="cu_nav">-->
					<ul class = "nav">
						
						<% if current_page? (setup_system_path) %>
							<li id= "navbar_setup" class="active">
						<% else %>
							<li id= "navbar_setup">
						<% end %>
							<%= link_to (t :setup), setup_system_path %>
						</li>
						
						<% if current_page? (create_users_path) %>
							<li id= "navbar_create_users" class="active">
						<% else %>
							<li id= "navbar_create_users">
						<% end %>
							<%= link_to (t :create_users), create_users_path %>
						</li>
					
						<% if current_page? (all_form_path) or current_page? (goals_path) or current_page? (indicators_path) or current_page? (projects_path)%>
							<li id ="navbar_framework" class="active">
						<% else %>
							<li id ="navbar_framework">
						<% end %>
							<%= link_to (t :framework), all_form_path %>
						</li>
						
						<% if current_page? (cu_review_path) %>
							<li id ="navbar_review" class="active">
						<% else %>
							<li id ="navbar_review">
						<% end %>
							<%= link_to (t :review), cu_review_path %>
						</li>
						
						<% if current_page? (all_data_path) or current_page? (graph_panel_path) %>
							<li id="navbar_report" class="active">
						<% else %>
							<li id="navbar_report">
						<% end %>
							<%= link_to (t :report), all_data_path %>
						</li>
						
					</ul>

					<!--     </div>-->
					<% end %>
					<% end %>

					<div class="btn-group pull-right right_navbar_drop">
						<a class="btn dropdown-toggle btn-inverse pull-right" data-toggle="dropdown"> <%= t '.user_settings' %> <span class="caret"></span> </a>
						<ul class="dropdown-menu">
							<li>
								<%= render 'devise/menu/login_items' %>
							</li>
							<li>
								<%= render 'devise/menu/registration_items' %>
							</li>
						</ul>
					</div>
					<% end %>

				</div>

			</div>
		</div>

		<div class="container body_container">
			<!-- Display messages For devise. -->
			<!-- <% if notice %>
			<div class="notice alert">
			<button type="button" class="close" data-dismiss="alert"><%= t 'times' %></button>
			<%= notice %>
			</div>

			<% end %>

			<% if alert %>
			<div class="alert">
			<button type="button" class="close" data-dismiss="alert"><%= t 'times' %></button>
			<%= alert %>
			</div>
			<% end %>-->
			<%= yield %>

		</div>
		<!-- /container -->

		<!--  <div class="container">
		<div class="footer">
		<center><%=t :footer_string%></center>
		</div>
		</div>-->
	</body>
</html>


app/views/layouts/provider.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Strategy Stroller</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <%= stylesheet_link_tag    "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
	<!-- Only use application for all js files or individual calls for each to prevent duplication
    <%= javascript_include_tag "custom" %>-->
    <!-- Added for cocoon gem -->
    <!--<%= javascript_include_tag :cocoon %>-->
  <!--<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>
  <script src="/assets/twitter/bootstrap/bootstrap-dropdown.js">-->

    <%= csrf_meta_tags %>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->
  </head>

  <body>



    <div class="navbar navbar-inverse navbar-fixed-top">
    
      <div class="navbar-inner">
      <div class="container">
        	<a class="brand" href="/"><%= t '.strategy_2' %></a>
            <% if signed_in? %>

           <% if current_user.controlling_unit == false %>
        	 <ul class = "nav">
              <% if current_page? (forms_composite_path) %>
              <li id= "navbar_define" class="active">
            <% else %>
              <li id= "navbar_define">
            <% end %>
              <%= link_to (t :define), forms_composite_path %>
            </li>

            <% if current_page? (forms_composite_update_path) %>
              <li id= "navbar_update" class="active">
            <% else %>
              <li id= "navbar_update">
            <% end %>
              <%= link_to (t :update), forms_composite_update_path %>
            </li>

          </ul>



          <% end %>
          <div class="btn-group pull-right right_navbar_drop">
						<a class="btn dropdown-toggle btn-inverse pull-right" data-toggle="dropdown"> <%= t '.user_settings' %> <span class="caret"></span> </a>
						<ul class="dropdown-menu">
							<li>
								<%= render 'devise/menu/login_items' %>
							</li>
							<li>
								<%= render 'devise/menu/registration_items' %>
							</li>
						</ul>
					</div>
      <% end %>
           

    </div>
      
  </div>
</div>


    <div class="container body_container">
      <!-- Display messages For devise. -->
   <!--     <% if notice %>
      <div class="notice alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
      </div>
      
      <% end %>
      
      <% if alert %>
      <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= alert %>
      </div>
      <% end %>-->
      <%= yield %>

    </div> <!-- /container -->

  <!--  <div class="container">
    <div class="footer">
    <center><%=t :footer_string%></center>
    </div>
    </div>-->
  </body>
</html>

app/views/layouts/sidebar.html.erb
 <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header"><%= t '.navigation' %></li>
              <li class="active"><a href="/home/index"><%= t '.home' %></a></li>
              <li><a href="/admin/login"><%= t '.admin_1' %></a></li>
              <li><a href="#"><%= t '.new_system' %></a></li>
              <li><a href="#"><%= t '.yearly_review' %></a></li>
              <li><a href="#"><%= t '.quality_check' %></a></li>
              <li><a href="#"><%= t '.monthly_report' %></a></li>
              <li><a href="#"><%= t '.quarterly' %></a></li>
              <li class="nav-header"><%= t '.context_menu' %></li>
              <%= yield :context_menu %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <%= yield %>
          </div>
        </div><!--/span-->
      </div><!--/row-->